matrix:
    include:
        - language: python
          python:
            - "3.6"
          install:
            - make install
          script:
            - make pytest

        - language: c
          compiler:
            - gcc
          script:
            - make c_test
